### ISSUE TITLE
Requires an appindicator library

### ISSUE THREAD

**Issue by sarahkittyy** [Yakkhini/Weye#1]
I wanted to use this with sway but I received a panic in main for, 'Can't detect any appindicator library.' I shouldn't need a system tray to run it I should be able to launch it from CLI and bind that to a hotkey in my sway config.

**Comment by Yakkhini** [comment]
Thanks for giving Weye a try 🥹! Currently I'm not maintain it because I switched my work environment to Hyprland & NixOS. If you want to use screenshot tool with a CLI way, I recommend [grimshot](https://github.com/OctopusET/sway-contrib). Actually, Weye is a wrap of this command.
